# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  node-version: '18.x'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Souce Code
        uses: actions/checkout@v3

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.node-version }}

      - name: Build Frontentd
        run: npm install
        working-directory: ./client

      - name: Build Backend
        run: npm install
        working-directory: ./server

      - name: Deploy Backend to Heroku
        uses: lucassarcanjo/heroku-deploy@2.1.17
        with:
          email: ${{ secrets.HEROKU_EMAIL }}
          api_key: ${{ secrets.HEROKU_API_KEY }}
          app_name: ${{ secrets.HEROKU_BACKEND_APP_NAME }}
          dockerfile_path: ./server